/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as GatheringsRouteImport } from './routes/gatherings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NewRouteImport } from './routes/new'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as GIdRouteImport } from './routes/g.$id'
import { Route as GIdIndexRouteImport } from './routes/g.$id.index'
import { Route as GIdAddRouteImport } from './routes/g.$id.add'
import { Route as GIdExpensesRouteImport } from './routes/g.$id.expenses'
import { Route as GIdRemindRouteImport } from './routes/g.$id.remind'
import { Route as GIdSettleRouteImport } from './routes/g.$id.settle'
import { Route as GIdSplitRouteImport } from './routes/g.$id.split'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringsRoute = GatheringsRouteImport.update({
  id: '/gatherings',
  path: '/gatherings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const GIdRoute = GIdRouteImport.update({
  id: '/g/$id',
  path: '/g/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GIdIndexRoute = GIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GIdRoute,
} as any)
const GIdAddRoute = GIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => GIdRoute,
} as any)
const GIdExpensesRoute = GIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => GIdRoute,
} as any)
const GIdRemindRoute = GIdRemindRouteImport.update({
  id: '/remind',
  path: '/remind',
  getParentRoute: () => GIdRoute,
} as any)
const GIdSettleRoute = GIdSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => GIdRoute,
} as any)
const GIdSplitRoute = GIdSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => GIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/gatherings': typeof GatheringsRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/scan': typeof ScanRoute
  '/welcome': typeof WelcomeRoute
  '/g/$id': typeof GIdRouteWithChildren
  '/g/$id/add': typeof GIdAddRoute
  '/g/$id/expenses': typeof GIdExpensesRoute
  '/g/$id/remind': typeof GIdRemindRoute
  '/g/$id/settle': typeof GIdSettleRoute
  '/g/$id/split': typeof GIdSplitRoute
  '/g/$id/': typeof GIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/gatherings': typeof GatheringsRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/scan': typeof ScanRoute
  '/welcome': typeof WelcomeRoute
  '/g/$id/add': typeof GIdAddRoute
  '/g/$id/expenses': typeof GIdExpensesRoute
  '/g/$id/remind': typeof GIdRemindRoute
  '/g/$id/settle': typeof GIdSettleRoute
  '/g/$id/split': typeof GIdSplitRoute
  '/g/$id': typeof GIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/gatherings': typeof GatheringsRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/scan': typeof ScanRoute
  '/welcome': typeof WelcomeRoute
  '/g/$id': typeof GIdRouteWithChildren
  '/g/$id/add': typeof GIdAddRoute
  '/g/$id/expenses': typeof GIdExpensesRoute
  '/g/$id/remind': typeof GIdRemindRoute
  '/g/$id/settle': typeof GIdSettleRoute
  '/g/$id/split': typeof GIdSplitRoute
  '/g/$id/': typeof GIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/gatherings'
    | '/history'
    | '/join'
    | '/more'
    | '/new'
    | '/quick'
    | '/scan'
    | '/welcome'
    | '/g/$id'
    | '/g/$id/add'
    | '/g/$id/expenses'
    | '/g/$id/remind'
    | '/g/$id/settle'
    | '/g/$id/split'
    | '/g/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/gatherings'
    | '/history'
    | '/join'
    | '/more'
    | '/new'
    | '/quick'
    | '/scan'
    | '/welcome'
    | '/g/$id/add'
    | '/g/$id/expenses'
    | '/g/$id/remind'
    | '/g/$id/settle'
    | '/g/$id/split'
    | '/g/$id'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/gatherings'
    | '/history'
    | '/join'
    | '/more'
    | '/new'
    | '/quick'
    | '/scan'
    | '/welcome'
    | '/g/$id'
    | '/g/$id/add'
    | '/g/$id/expenses'
    | '/g/$id/remind'
    | '/g/$id/settle'
    | '/g/$id/split'
    | '/g/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  GatheringsRoute: typeof GatheringsRoute
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRoute
  MoreRoute: typeof MoreRoute
  NewRoute: typeof NewRoute
  QuickRoute: typeof QuickRoute
  ScanRoute: typeof ScanRoute
  WelcomeRoute: typeof WelcomeRoute
  GIdRoute: typeof GIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatherings': {
      id: '/gatherings'
      path: '/gatherings'
      fullPath: '/gatherings'
      preLoaderRoute: typeof GatheringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$id': {
      id: '/g/$id'
      path: '/g/$id'
      fullPath: '/g/$id'
      preLoaderRoute: typeof GIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$id/': {
      id: '/g/$id/'
      path: '/'
      fullPath: '/g/$id/'
      preLoaderRoute: typeof GIdIndexRouteImport
      parentRoute: typeof GIdRoute
    }
    '/g/$id/add': {
      id: '/g/$id/add'
      path: '/add'
      fullPath: '/g/$id/add'
      preLoaderRoute: typeof GIdAddRouteImport
      parentRoute: typeof GIdRoute
    }
    '/g/$id/expenses': {
      id: '/g/$id/expenses'
      path: '/expenses'
      fullPath: '/g/$id/expenses'
      preLoaderRoute: typeof GIdExpensesRouteImport
      parentRoute: typeof GIdRoute
    }
    '/g/$id/remind': {
      id: '/g/$id/remind'
      path: '/remind'
      fullPath: '/g/$id/remind'
      preLoaderRoute: typeof GIdRemindRouteImport
      parentRoute: typeof GIdRoute
    }
    '/g/$id/settle': {
      id: '/g/$id/settle'
      path: '/settle'
      fullPath: '/g/$id/settle'
      preLoaderRoute: typeof GIdSettleRouteImport
      parentRoute: typeof GIdRoute
    }
    '/g/$id/split': {
      id: '/g/$id/split'
      path: '/split'
      fullPath: '/g/$id/split'
      preLoaderRoute: typeof GIdSplitRouteImport
      parentRoute: typeof GIdRoute
    }
  }
}

interface GIdRouteChildren {
  GIdAddRoute: typeof GIdAddRoute
  GIdExpensesRoute: typeof GIdExpensesRoute
  GIdRemindRoute: typeof GIdRemindRoute
  GIdSettleRoute: typeof GIdSettleRoute
  GIdSplitRoute: typeof GIdSplitRoute
  GIdIndexRoute: typeof GIdIndexRoute
}

const GIdRouteChildren: GIdRouteChildren = {
  GIdAddRoute: GIdAddRoute,
  GIdExpensesRoute: GIdExpensesRoute,
  GIdRemindRoute: GIdRemindRoute,
  GIdSettleRoute: GIdSettleRoute,
  GIdSplitRoute: GIdSplitRoute,
  GIdIndexRoute: GIdIndexRoute,
}

const GIdRouteWithChildren = GIdRoute._addFileChildren(GIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  GatheringsRoute: GatheringsRoute,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRoute,
  MoreRoute: MoreRoute,
  NewRoute: NewRoute,
  QuickRoute: QuickRoute,
  ScanRoute: ScanRoute,
  WelcomeRoute: WelcomeRoute,
  GIdRoute: GIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
